import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('iris.txt', sep=",", header=None)
data.columns=["sep_length", "sep_width", "pet_length", "pet_width", "class"]

print (data)
#IRIS_SETOSA
print("Iris_setosa Mean")
print(data[['sep_length','sep_width','pet_length','pet_width']].loc[data['class']=='Iris-setosa'].mean())
print("Iris_setosa Max")
print(data[['sep_length','sep_width','pet_length','pet_width']].loc[data['class']=='Iris-setosa'].max())
print("Iris_setosa Min")
print(data[['sep_length','sep_width','pet_length','pet_width']].loc[data['class']=='Iris-setosa'].min())

#IRIS_VIRGINICA
print("iris_virginica Mean")
print(data[['sep_length','sep_width','pet_length','pet_width']].loc[data['class']=='Iris-virginica'].mean())
print("iris_virginica Max")
print(data[['sep_length','sep_width','pet_length','pet_width']].loc[data['class']=='Iris-virginica'].max())
print("iris_virginica Min")
print(data[['sep_length','sep_width','pet_length','pet_width']].loc[data['class']=='Iris-virginica'].min())

#IRIS_VERSICOLOR
print("Iris_versicolor mean")
print(data[['sep_length','sep_width','pet_length','pet_width']].loc[data['class']=='Iris-versicolor'].mean())
print("Iris_versicolor MAX")
print(data[['sep_length','sep_width','pet_length','pet_width']].loc[data['class']=='Iris-versicolor'].max())
print("Iris_versicolor Min")
print(data[['sep_length','sep_width','pet_length','pet_width']].loc[data['class']=='Iris-versicolor'].min())
print(data[['sep_length','sep_width','pet_length','pet_width']].mean())

fig = plt.figure()
ax1 = fig.add_subplot(111)
ax1.scatter(x=data[['sep_length']].loc[data['class']=='Iris-setosa'],y=data[['sep_width']].loc[data['class']=='Iris-setosa'],s=10,c='b',marker="s")
ax1.scatter(x=data[['sep_length']].loc[data['class']=='Iris-virginica'],y=data[['sep_width']].loc[data['class']=='Iris-virginica'],s=10,c='r',marker="s")
ax1.scatter(x=data[['sep_length']].loc[data['class']=='Iris-versicolor'],y=data[['sep_width']].loc[data['class']=='Iris-versicolor'],s=10,c='g',marker="s")
plt.xlabel("sep_length")
plt.ylabel("sep_width")
plt.title("sep length and width")
data[['sep_length','sep_width']].loc[data['class']=='Iris-setosa'].plot(kind='scatter',x='sep_length',y='sep_width',color='red')
data[['sep_length','sep_width']].loc[data['class']=='Iris-virginica'].plot(kind='scatter',x='sep_length',y='sep_width',color='blue')
data[['sep_length','sep_width']].loc[data['class']=='Iris-versicolor'].plot(kind='scatter',x='sep_length',y='sep_width',color='black')

fig2 = plt.figure()
ax2 = fig2.add_subplot(111)
ax2.scatter(x=data[['pet_length']].loc[data['class']=='Iris-setosa'],y=data[['pet_width']].loc[data['class']=='Iris-setosa'],s=10,c='b',marker="s")
ax2.scatter(x=data[['pet_length']].loc[data['class']=='Iris-virginica'],y=data[['pet_width']].loc[data['class']=='Iris-virginica'],s=10,c='r',marker="s")
ax2.scatter(x=data[['pet_length']].loc[data['class']=='Iris-versicolor'],y=data[['pet_width']].loc[data['class']=='Iris-versicolor'],s=10,c='g',marker="s")
plt.xlabel("pet_length")
plt.ylabel("pet_width")
plt.title("pet length and width")

fig3 = plt.figure()
ax3 = fig3.add_subplot(111)
ax3.scatter(x=data[['sep_length']].loc[data['class']=='Iris-setosa'],y=data[['pet_width']].loc[data['class']=='Iris-setosa'],s=10,c='b',marker="s")
ax3.scatter(x=data[['sep_length']].loc[data['class']=='Iris-virginica'],y=data[['pet_width']].loc[data['class']=='Iris-virginica'],s=10,c='r',marker="s")
ax3.scatter(x=data[['sep_length']].loc[data['class']=='Iris-versicolor'],y=data[['pet_width']].loc[data['class']=='Iris-versicolor'],s=10,c='g',marker="s")
plt.xlabel("sep_length")
plt.ylabel("pet_width")
plt.title("sep length and pet width")
data[['pet_length','pet_width']].loc[data['class']=='Iris-setosa'].plot(kind='scatter',x='pet_length',y='pet_width',color='red')
data[['pet_length','pet_width']].loc[data['class']=='Iris-virginica'].plot(kind='scatter',x='pet_length',y='pet_width',color='blue')
data[['pet_length','pet_width']].loc[data['class']=='Iris-versicolor'].plot(kind='scatter',x='pet_length',y='pet_width',color='black')
fig4 = plt.figure()
ax4 = fig4.add_subplot(111)
ax4.scatter(x=data[['pet_length']].loc[data['class']=='Iris-setosa'],y=data[['sep_width']].loc[data['class']=='Iris-setosa'],s=10,c='b',marker="s")
ax4.scatter(x=data[['pet_length']].loc[data['class']=='Iris-virginica'],y=data[['sep_width']].loc[data['class']=='Iris-virginica'],s=10,c='r',marker="s")
ax4.scatter(x=data[['pet_length']].loc[data['class']=='Iris-versicolor'],y=data[['sep_width']].loc[data['class']=='Iris-versicolor'],s=10,c='g',marker="s")

fig5 = plt.figure()
ax5 = fig5.add_subplot(111)
ax5.scatter(x=data[['pet_length']].loc[data['class']=='Iris-setosa'],y=data[['sep_length']].loc[data['class']=='Iris-setosa'],s=10,c='b',marker="s")
ax5.scatter(x=data[['pet_length']].loc[data['class']=='Iris-virginica'],y=data[['sep_length']].loc[data['class']=='Iris-virginica'],s=10,c='r',marker="s")
ax5.scatter(x=data[['pet_length']].loc[data['class']=='Iris-versicolor'],y=data[['sep_length']].loc[data['class']=='Iris-versicolor'],s=10,c='g',marker="s")
plt.xlabel("pet_length")
plt.ylabel("sep_length")
plt.title("sep length and pet length")
plt.show()